name: CI / CD

on: [push]

jobs:
  web-app-build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8 for web-app
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install web-app dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r web-app/requirements.txt
        working-directory: ./web-app

      - name: Run web-app tests
        run: pytest
        working-directory: ./web-app

  machine-learning-client-build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8 for machine-learning-client
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install machine-learning-client dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r machine-learning-client/requirements.txt
        working-directory: ./machine-learning-client

      - name: Run machine-learning-client tests
        run: pytest
        working-directory: ./machine-learning-client
